-- MySQL Script generated by MySQL Workbench
-- Thu 02 Nov 2023 12:07:59 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS HealthManagementSystemDB;
CREATE SCHEMA HealthManagementSystemDB;
USE HealthManagementSystemDB;
-- -----------------------------------------------------
-- Table `HealthData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HealthData` ;

CREATE TABLE IF NOT EXISTS `HealthData` (
  `health_data_id` INT NOT NULL AUTO_INCREMENT,
  `height` INT UNSIGNED NULL,
  `weight` INT UNSIGNED NULL,
  `blood_pressure` INT UNSIGNED NULL,
  `breathing_rate` INT UNSIGNED NULL,
  `current_heart_rate` INT UNSIGNED NULL,
  PRIMARY KEY (`health_data_id`),
  UNIQUE INDEX `health_data_id_UNIQUE` (`health_data_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Admin` ;

CREATE TABLE IF NOT EXISTS `Admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `admin_id_UNIQUE` (`admin_id` ASC) VISIBLE,
  INDEX `fk_admin_user_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_admin_user`
    FOREIGN KEY (`user`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Patient` ;

CREATE TABLE IF NOT EXISTS `Patient` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`patient_id`),
  UNIQUE INDEX `patient_id_UNIQUE` (`patient_id` ASC) VISIBLE,
  INDEX `fk_patient_user_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_patient_user`
    FOREIGN KEY (`user`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LicenceNum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LicenceNum` ;

CREATE TABLE IF NOT EXISTS `LicenceNum` (
  `licence_id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(255) NOT NULL,
  `creation_date` DATE NULL,
  PRIMARY KEY (`licence_id`),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC) VISIBLE,
  UNIQUE INDEX `licence_id_UNIQUE` (`licence_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Doctor` ;

CREATE TABLE IF NOT EXISTS `Doctor` (
  `doctor_id` INT NOT NULL AUTO_INCREMENT,
  `licence` INT NOT NULL,
  `speciality` VARCHAR(255) NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`doctor_id`),
  UNIQUE INDEX `doctor_id_UNIQUE` (`doctor_id` ASC) VISIBLE,
  UNIQUE INDEX `licence_UNIQUE` (`licence` ASC) VISIBLE,
  INDEX `fk_doctor_user_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_licence`
    FOREIGN KEY (`licence`)
    REFERENCES `LicenceNum` (`licence_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_doctor_user`
    FOREIGN KEY (`user`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Role` ;

CREATE TABLE IF NOT EXISTS `Role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(45) NULL,
  `admin` INT NULL,
  `patient` INT NULL,
  `doctor` INT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_admin_idx` (`admin` ASC) VISIBLE,
  INDEX `fk_patient_idx` (`patient` ASC) VISIBLE,
  INDEX `fk_doctor_idx` (`doctor` ASC) VISIBLE,
  CONSTRAINT `fk_admin`
    FOREIGN KEY (`admin`)
    REFERENCES `Admin` (`admin_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_patient`
    FOREIGN KEY (`patient`)
    REFERENCES `Patient` (`patient_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_doctor`
    FOREIGN KEY (`doctor`)
    REFERENCES `Doctor` (`doctor_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `health_metric_data_id` INT NULL,
  `role_id` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_health_metric_data_idx` (`health_metric_data_id` ASC) VISIBLE,
  INDEX `fk_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_health_metric_data`
    FOREIGN KEY (`health_metric_data_id`)
    REFERENCES `HealthData` (`health_data_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `Role` (`role_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialNumber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SocialNumber` ;

CREATE TABLE IF NOT EXISTS `SocialNumber` (
  `social_number_id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`social_number_id`),
  UNIQUE INDEX `social_number_id_UNIQUE` (`social_number_id` ASC) VISIBLE,
  UNIQUE INDEX `value_UNIQUE` (`value` ASC) VISIBLE,
  UNIQUE INDEX `user_UNIQUE` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_user_social_number`
    FOREIGN KEY (`user`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OS` ;

CREATE TABLE IF NOT EXISTS `OS` (
  `os_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`os_id`),
  UNIQUE INDEX `os_id_UNIQUE` (`os_id` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Language` ;

CREATE TABLE IF NOT EXISTS `Language` (
  `language_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`language_id`),
  UNIQUE INDEX `language_id_UNIQUE` (`language_id` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Region` ;

CREATE TABLE IF NOT EXISTS `Region` (
  `region_id` INT NOT NULL AUTO_INCREMENT,
  `code_area` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`region_id`),
  UNIQUE INDEX `region_id_UNIQUE` (`region_id` ASC) VISIBLE,
  UNIQUE INDEX `code_area_UNIQUE` (`code_area` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `role` INT NULL,
  `region` INT NULL,
  `user_health_data` INT NULL,
  `os` INT NULL,
  `language` INT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `fk_role_idx` (`role` ASC) VISIBLE,
  INDEX `fk_os_idx` (`os` ASC) VISIBLE,
  INDEX `fk_language_idx` (`language` ASC) VISIBLE,
  INDEX `fk_region_idx` (`region` ASC) VISIBLE,
  UNIQUE INDEX `user_health_data_UNIQUE` (`user_health_data` ASC) VISIBLE,
  CONSTRAINT `fk_account_role`
    FOREIGN KEY (`role`)
    REFERENCES `Role` (`role_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_os`
    FOREIGN KEY (`os`)
    REFERENCES `OS` (`os_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_language`
    FOREIGN KEY (`language`)
    REFERENCES `Language` (`language_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_region`
    FOREIGN KEY (`region`)
    REFERENCES `Region` (`region_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Meal` ;

CREATE TABLE IF NOT EXISTS `Meal` (
  `meal_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `caloric_value` INT UNSIGNED NULL,
  `date` VARCHAR(255) NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`meal_id`),
  UNIQUE INDEX `meal_id_UNIQUE` (`meal_id` ASC) VISIBLE,
  INDEX `fk_user_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SportActivity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SportActivity` ;

CREATE TABLE IF NOT EXISTS `SportActivity` (
  `sport_activity_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `duration` INT UNSIGNED NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`sport_activity_id`),
  UNIQUE INDEX `sport_activity_id_UNIQUE` (`sport_activity_id` ASC) VISIBLE,
  INDEX `fk_user_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_sport_activity_user`
    FOREIGN KEY (`user`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HeartRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HeartRate` ;

CREATE TABLE IF NOT EXISTS `HeartRate` (
  `heart_rate_id` INT NOT NULL AUTO_INCREMENT,
  `heart_rate` INT UNSIGNED NULL,
  `date` DATETIME NULL,
  `health_metric` INT NOT NULL,
  PRIMARY KEY (`heart_rate_id`),
  UNIQUE INDEX `heart_rate_id_UNIQUE` (`heart_rate_id` ASC) VISIBLE,
  INDEX `fk_health_data_idx` (`health_metric` ASC) VISIBLE,
  UNIQUE INDEX `date_UNIQUE` (`date` ASC) VISIBLE,
  CONSTRAINT `fk_health_data`
    FOREIGN KEY (`health_metric`)
    REFERENCES `HealthData` (`health_data_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Action` ;

CREATE TABLE IF NOT EXISTS `Action` (
  `action_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`action_id`),
  UNIQUE INDEX `action_id_UNIQUE` (`action_id` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event` ;

CREATE TABLE IF NOT EXISTS `Event` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `date` VARCHAR(45) NOT NULL,
  `place` VARCHAR(45) NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE INDEX `event_id_UNIQUE` (`event_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Device` ;

CREATE TABLE IF NOT EXISTS `Device` (
  `device_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`device_id`),
  UNIQUE INDEX `device_id_UNIQUE` (`device_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Training`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Training` ;

CREATE TABLE IF NOT EXISTS `Training` (
  `training_id` INT NOT NULL AUTO_INCREMENT,
  `duration` INT UNSIGNED NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`training_id`),
  UNIQUE INDEX `training_id_UNIQUE` (`training_id` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthActivity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HealthActivity` ;

CREATE TABLE IF NOT EXISTS `HealthActivity` (
  `health_activity_id` INT NOT NULL AUTO_INCREMENT,
  `duration` INT UNSIGNED NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`health_activity_id`),
  UNIQUE INDEX `health_activity_id_UNIQUE` (`health_activity_id` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodCategory` ;

CREATE TABLE IF NOT EXISTS `FoodCategory` (
  `food_category_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`food_category_id`),
  UNIQUE INDEX `food_category_id_UNIQUE` (`food_category_id` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodExpert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodExpert` ;

CREATE TABLE IF NOT EXISTS `FoodExpert` (
  `food_expert_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `region` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`food_expert_id`),
  UNIQUE INDEX `food_expert_id_UNIQUE` (`food_expert_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Coach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Coach` ;

CREATE TABLE IF NOT EXISTS `Coach` (
  `coach_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `sport` VARCHAR(255) NOT NULL,
  `region` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`coach_id`),
  UNIQUE INDEX `coach_id_UNIQUE` (`coach_id` ASC) VISIBLE,
  UNIQUE INDEX `Coachcol_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Place` ;

CREATE TABLE IF NOT EXISTS `Place` (
  `place_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `position` VARCHAR(255) NOT NULL,
  `region` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`place_id`),
  UNIQUE INDEX `place_id_UNIQUE` (`place_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccountRegisterToEvent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountRegisterToEvent` ;

CREATE TABLE IF NOT EXISTS `AccountRegisterToEvent` (
  `user_register_to_event_id` INT NOT NULL AUTO_INCREMENT,
  `account` INT NOT NULL,
  `event` INT NOT NULL,
  PRIMARY KEY (`user_register_to_event_id`),
  UNIQUE INDEX `user_register_to_event_id_UNIQUE` (`user_register_to_event_id` ASC) VISIBLE,
  INDEX `fk_account_idx` (`account` ASC) VISIBLE,
  INDEX `fk_event_idx` (`event` ASC) VISIBLE,
  CONSTRAINT `fk_account`
    FOREIGN KEY (`account`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_event`
    FOREIGN KEY (`event`)
    REFERENCES `Event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccountAssociateToDevice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountAssociateToDevice` ;

CREATE TABLE IF NOT EXISTS `AccountAssociateToDevice` (
  `account_associate_to_device_id` INT NOT NULL AUTO_INCREMENT,
  `account` INT NOT NULL,
  `device` INT NOT NULL,
  PRIMARY KEY (`account_associate_to_device_id`),
  UNIQUE INDEX `account_associate_to_device_id_UNIQUE` (`account_associate_to_device_id` ASC) VISIBLE,
  INDEX `fk_account_idx` (`account` ASC) VISIBLE,
  INDEX `fk_device_idx` (`device` ASC) VISIBLE,
  CONSTRAINT `fk_associate_account`
    FOREIGN KEY (`account`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_device`
    FOREIGN KEY (`device`)
    REFERENCES `Device` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccountSaveTraining`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountSaveTraining` ;

CREATE TABLE IF NOT EXISTS `AccountSaveTraining` (
  `account_save_training_id` INT NOT NULL AUTO_INCREMENT,
  `account` INT NOT NULL,
  `training` INT NOT NULL,
  PRIMARY KEY (`account_save_training_id`),
  UNIQUE INDEX `account_save_training_id_UNIQUE` (`account_save_training_id` ASC) VISIBLE,
  INDEX `fk_account_idx` (`account` ASC) VISIBLE,
  INDEX `fk_training_idx` (`training` ASC) VISIBLE,
  CONSTRAINT `fk_save_training_account`
    FOREIGN KEY (`account`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_save_training_training`
    FOREIGN KEY (`training`)
    REFERENCES `Training` (`training_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccountSaveHealthActivity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountSaveHealthActivity` ;

CREATE TABLE IF NOT EXISTS `AccountSaveHealthActivity` (
  `account_save_health_activity_id` INT NOT NULL AUTO_INCREMENT,
  `account` INT NOT NULL,
  `health_activity` INT NOT NULL,
  PRIMARY KEY (`account_save_health_activity_id`),
  UNIQUE INDEX `account_save_training_id_UNIQUE` (`account_save_health_activity_id` ASC) VISIBLE,
  INDEX `fk_account_idx` (`account` ASC) VISIBLE,
  INDEX `fk_health_activity_idx` (`health_activity` ASC) VISIBLE,
  CONSTRAINT `fk_save_health_activity_account`
    FOREIGN KEY (`account`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_save_health_activity_health_activity`
    FOREIGN KEY (`health_activity`)
    REFERENCES `HealthActivity` (`health_activity_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccountSaveCoach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountSaveCoach` ;

CREATE TABLE IF NOT EXISTS `AccountSaveCoach` (
  `account_save_coach_id` INT NOT NULL AUTO_INCREMENT,
  `account` INT NOT NULL,
  `coach` INT NOT NULL,
  PRIMARY KEY (`account_save_coach_id`),
  UNIQUE INDEX `account_save_training_id_UNIQUE` (`account_save_coach_id` ASC) VISIBLE,
  INDEX `fk_coach_idx` (`coach` ASC) VISIBLE,
  INDEX `fk_account_idx` (`account` ASC) VISIBLE,
  CONSTRAINT `fk_save_coach_account`
    FOREIGN KEY (`account`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_save_coach_coach`
    FOREIGN KEY (`coach`)
    REFERENCES `Coach` (`coach_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccountSavePlace`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountSavePlace` ;

CREATE TABLE IF NOT EXISTS `AccountSavePlace` (
  `account_save_place_id` INT NOT NULL AUTO_INCREMENT,
  `account` INT NOT NULL,
  `place` INT NOT NULL,
  PRIMARY KEY (`account_save_place_id`),
  UNIQUE INDEX `account_save_training_id_UNIQUE` (`account_save_place_id` ASC) VISIBLE,
  INDEX `fk_account_idx` (`account` ASC) VISIBLE,
  INDEX `fk_place_idx` (`place` ASC) VISIBLE,
  CONSTRAINT `fk_save_place_account`
    FOREIGN KEY (`account`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_save_place_place`
    FOREIGN KEY (`place`)
    REFERENCES `Place` (`place_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccountSaveFoodExpert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountSaveFoodExpert` ;

CREATE TABLE IF NOT EXISTS `AccountSaveFoodExpert` (
  `account_save_food_expert_id` INT NOT NULL AUTO_INCREMENT,
  `account` INT NOT NULL,
  `food_expert` INT NOT NULL,
  PRIMARY KEY (`account_save_food_expert_id`),
  UNIQUE INDEX `account_save_training_id_UNIQUE` (`account_save_food_expert_id` ASC) VISIBLE,
  INDEX `fk_food_expert_idx` (`food_expert` ASC) VISIBLE,
  INDEX `fk_account_idx` (`account` ASC) VISIBLE,
  CONSTRAINT `fk_save_food_expert_account`
    FOREIGN KEY (`account`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_save_food_expert_food_expert`
    FOREIGN KEY (`food_expert`)
    REFERENCES `FoodExpert` (`food_expert_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccountSaveFoodCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountSaveFoodCategory` ;

CREATE TABLE IF NOT EXISTS `AccountSaveFoodCategory` (
  `account_save_food_category_id` INT NOT NULL AUTO_INCREMENT,
  `account` INT NOT NULL,
  `food_category` INT NOT NULL,
  PRIMARY KEY (`account_save_food_category_id`),
  UNIQUE INDEX `account_save_training_id_UNIQUE` (`account_save_food_category_id` ASC) VISIBLE,
  INDEX `fk_account_idx` (`account` ASC) VISIBLE,
  INDEX `fk_food_category_idx` (`food_category` ASC) VISIBLE,
  CONSTRAINT `fk_save_food_category_account`
    FOREIGN KEY (`account`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_save_food_category_food_category`
    FOREIGN KEY (`food_category`)
    REFERENCES `FoodCategory` (`food_category_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ActionLinkToRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ActionLinkToRole` ;

CREATE TABLE IF NOT EXISTS `ActionLinkToRole` (
  `action_link_to_role` INT NOT NULL AUTO_INCREMENT,
  `action` INT NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`action_link_to_role`),
  UNIQUE INDEX `action_link_to_role_UNIQUE` (`action_link_to_role` ASC) VISIBLE,
  INDEX `fk_role_idx` (`role` ASC) VISIBLE,
  INDEX `fk_action_idx` (`action` ASC) VISIBLE,
  CONSTRAINT `fk_action_link_role`
    FOREIGN KEY (`role`)
    REFERENCES `Role` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_action_link_action`
    FOREIGN KEY (`action`)
    REFERENCES `Action` (`action_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccountHasAction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountHasAction` ;

CREATE TABLE IF NOT EXISTS `AccountHasAction` (
  `account_has_action_id` INT NOT NULL AUTO_INCREMENT,
  `account` INT NOT NULL,
  `action` INT NOT NULL,
  PRIMARY KEY (`account_has_action_id`),
  UNIQUE INDEX `account_has_action_id_UNIQUE` (`account_has_action_id` ASC) VISIBLE,
  INDEX `fk_account_idx` (`account` ASC) VISIBLE,
  INDEX `fk_action_idx` (`action` ASC) VISIBLE,
  CONSTRAINT `fk_has_action_account`
    FOREIGN KEY (`account`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_has_action_action`
    FOREIGN KEY (`action`)
    REFERENCES `Action` (`action_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserLinkToDoctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserLinkToDoctor` ;

CREATE TABLE IF NOT EXISTS `UserLinkToDoctor` (
  `user_link_to_doctor_id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `doctor` INT NOT NULL,
  PRIMARY KEY (`user_link_to_doctor_id`),
  UNIQUE INDEX `user_link_to_doctor_id_UNIQUE` (`user_link_to_doctor_id` ASC) VISIBLE,
  INDEX `fk_user_link_to_doctor_user_idx` (`user` ASC) VISIBLE,
  INDEX `fk_user_link_to_doctor_doctor_idx` (`doctor` ASC) VISIBLE,
  CONSTRAINT `fk_user_link_to_doctor_user`
    FOREIGN KEY (`user`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_link_to_doctor_doctor`
    FOREIGN KEY (`doctor`)
    REFERENCES `Doctor` (`doctor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserLinkToUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserLinkToUser` ;

CREATE TABLE IF NOT EXISTS `UserLinkToUser` (
  `user_link_to_user_id` INT NOT NULL AUTO_INCREMENT,
  `userA` INT NOT NULL,
  `userB` INT NOT NULL,
  PRIMARY KEY (`user_link_to_user_id`),
  UNIQUE INDEX `user_link_to_user_id_UNIQUE` (`user_link_to_user_id` ASC) VISIBLE,
  INDEX `fk_user_link_to_user_a_idx` (`userA` ASC) VISIBLE,
  INDEX `fk_user_link_to_user_b_idx` (`userB` ASC) VISIBLE,
  CONSTRAINT `fk_user_link_to_user_a`
    FOREIGN KEY (`userA`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_link_to_user_b`
    FOREIGN KEY (`userB`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
